Add scripts to setup PXE boot for upstream CI
ppc64le-cloud/hypershift-agent-automation pull request #2
Opened 2023-07-27 05:40 UTC by dharaneeshvrd

2023-07-27 05:40 UTC, dharaneeshvrd commented
/cc @mkumatag

2023-07-31 06:02 UTC, mkumatag requested changes

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/cleanup-pxe-boot.sh
> +set -x
this will dump lot of logs, do we really need this?

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/cleanup-pxe-boot.sh
> +NODE_COUNT=$2
can we add code to throw an error message if no sufficient args passed to the script

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/cleanup-pxe-boot.sh
> +rm -rf /var/lib/tftpboot/images/${CLUSTER_NAME}
just make sure to check for non nil for the `CLUSTER_NAME` before triggering the rm call, you may end up deleting everything in the parent directory

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/cleanup-pxe-boot.sh
> +
have the restart dhcp here just after the modification

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/grub-menu.template
> +    fi
add newline in the end

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +
can we add code to throw an error message if no sufficient args passed to the script

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +
add the comment here with script usage details like syntax, param etc with some explanation about the script as well.

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +IFS=','
add more comments here about the following for loop and the sample context you are parsing

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +    CONFIG=$(cat /root/agent-ci/scripts/grub-menu.template | envsubst)
it will be good if you can consider handling that root_dir in a variable, because this script will not work when you clone it in a different dir, lets take care of that everywhere

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +sed -i 's/initrd/\
add comment for this sed

2023-07-31 06:02 UTC, mkumatag commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +
move tftp service restart here

2023-07-31 10:10 UTC, dharaneeshvrd reviewed
Addressed the comments 
ptal @mkumatag

2023-07-31 10:10 UTC, dharaneeshvrd commented on hack/upstream-ci-scripts/cleanup-pxe-boot.sh
> +set -x
Yeah for debug purpose kept it, many upstream workflows has this flag set. IMO we can also keep it.

2023-07-31 10:10 UTC, dharaneeshvrd commented on hack/upstream-ci-scripts/cleanup-pxe-boot.sh
> +rm -rf /var/lib/tftpboot/images/${CLUSTER_NAME}
Added CLUSTER_NAME not empty validation

2023-07-31 10:10 UTC, dharaneeshvrd commented on hack/upstream-ci-scripts/cleanup-pxe-boot.sh
> +
Done

2023-07-31 10:10 UTC, dharaneeshvrd commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +
Added description and usage info

2023-07-31 10:10 UTC, dharaneeshvrd commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +
Added the validation

2023-07-31 10:10 UTC, dharaneeshvrd commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +IFS=','
Added at usage block

2023-07-31 10:10 UTC, dharaneeshvrd commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +sed -i 's/initrd/\
Added

2023-07-31 10:10 UTC, dharaneeshvrd commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +
Done

2023-07-31 10:13 UTC, dharaneeshvrd commented on hack/upstream-ci-scripts/setup-pxe-boot.sh
> +    CONFIG=$(cat /root/agent-ci/scripts/grub-menu.template | envsubst)
removed the root dir reference, assuming that the files would reside in same dir.

2023-07-31 12:15 UTC, mkumatag commented on hack/upstream-ci-scripts/ip-forward.sh
> +#!/bin/bash -x
for later: lets explore how to make this run every boot

2023-07-31 12:18 UTC, mkumatag approved these changes
for now it looks okay, in future we can explore ansible to do this work from the CI container itself.

2023-09-08 13:09 UTC, merged